from opcua import Server
from opcua import ua
from opcua import Client
from random import randint
import datetime
import time

server = Server()
url = "opc.tcp://0.0.0.0:8899/freeopcua/server/"
server.set_endpoint(url)

name="OPC_UA_SERVER"
addspace = server.register_namespace(name)

#Define Variant Data Type  2 = Integer ; 4 = float
variant = None
variant = ua.Variant(0, ua.VariantType.Int16)

variant2 = None
variant2 = ua.Variant(0, ua.VariantType.Float)



node = server.get_objects_node()
Param = node.add_object(addspace,"PF")


BUS_1_BUS_17KV_BUS_1_V = Param.add_variable(addspace,"BUS_1_BUS_17KV_BUS_1_V",variant2)
BUS_1_BUS_17KV_BUS_1_V.set_writable(True)
BUS_1_BUS_17KV_BUS_1_VMAX_RES = Param.add_variable(addspace,"BUS_1_BUS_17KV_BUS_1_VMAX_RES",variant2)
BUS_1_BUS_17KV_BUS_1_VMAX_RES.set_writable(True)
BUS_1_BUS_17KV_BUS_1_VMIN_RES = Param.add_variable(addspace,"BUS_1_BUS_17KV_BUS_1_VMIN_RES",variant2)
BUS_1_BUS_17KV_BUS_1_VMIN_RES.set_writable(True)
BUS_1_BUS_17KV_BUS_1_V_RES = Param.add_variable(addspace,"BUS_1_BUS_17KV_BUS_1_V_RES",variant2)
BUS_1_BUS_17KV_BUS_1_V_RES.set_writable(True)
BUS_1_CB_17KV_BREAKER1_BK = Param.add_variable(addspace,"BUS_1_CB_17KV_BREAKER1_BK",variant)
BUS_1_CB_17KV_BREAKER1_BK.set_writable(True)
BUS_1_CB_17KV_BREAKER1_BK_RES = Param.add_variable(addspace,"BUS_1_CB_17KV_BREAKER1_BK_RES",variant)
BUS_1_CB_17KV_BREAKER1_BK_RES.set_writable(True)
BUS_1_DISC_17KV_DISCONNECTOR1_BK = Param.add_variable(addspace,"BUS_1_DISC_17KV_DISCONNECTOR1_BK",variant)
BUS_1_DISC_17KV_DISCONNECTOR1_BK.set_writable(True)
BUS_1_DISC_17KV_DISCONNECTOR1_BK_RES = Param.add_variable(addspace,"BUS_1_DISC_17KV_DISCONNECTOR1_BK_RES",variant)
BUS_1_DISC_17KV_DISCONNECTOR1_BK_RES.set_writable(True)
BUS_1_GEN_17KV_G1_P_RES = Param.add_variable(addspace,"BUS_1_GEN_17KV_G1_P_RES",variant2)
BUS_1_GEN_17KV_G1_P_RES.set_writable(True)
BUS_1_GEN_17KV_G1_Q_RES = Param.add_variable(addspace,"BUS_1_GEN_17KV_G1_Q_RES",variant2)
BUS_1_GEN_17KV_G1_Q_RES.set_writable(True)
BUS_1_GEN_17KV_G1_V_CTRL = Param.add_variable(addspace,"BUS_1_GEN_17KV_G1_V_CTRL",variant2)
BUS_1_GEN_17KV_G1_V_CTRL.set_writable(True)
BUS_1_GEN_17KV_G1_V_RES = Param.add_variable(addspace,"BUS_1_GEN_17KV_G1_V_RES",variant2)
BUS_1_GEN_17KV_G1_V_RES.set_writable(True)
BUS_1_SWITCH_17KV_BUS_1_CUB_1_BK = Param.add_variable(addspace,"BUS_1_SWITCH_17KV_BUS_1_CUB_1_BK",variant)
BUS_1_SWITCH_17KV_BUS_1_CUB_1_BK.set_writable(True)
BUS_1_SWITCH_17KV_BUS_1_CUB_1_BK_RES = Param.add_variable(addspace,"BUS_1_SWITCH_17KV_BUS_1_CUB_1_BK_RES",variant)
BUS_1_SWITCH_17KV_BUS_1_CUB_1_BK_RES.set_writable(True)
BUS_1_TR2_17KV_T1_LD_RES = Param.add_variable(addspace,"BUS_1_TR2_17KV_T1_LD_RES",variant2)
BUS_1_TR2_17KV_T1_LD_RES.set_writable(True)
BUS_1_TR2_17KV_T1_MXL_RES = Param.add_variable(addspace,"BUS_1_TR2_17KV_T1_MXL_RES",variant2)
BUS_1_TR2_17KV_T1_MXL_RES.set_writable(True)
BUS_1_TR2_17KV_T1_P = Param.add_variable(addspace,"BUS_1_TR2_17KV_T1_P",variant2)
BUS_1_TR2_17KV_T1_P.set_writable(True)
BUS_1_TR2_17KV_T1_P_RES = Param.add_variable(addspace,"BUS_1_TR2_17KV_T1_P_RES",variant2)
BUS_1_TR2_17KV_T1_P_RES.set_writable(True)
BUS_1_TR2_17KV_T1_Q = Param.add_variable(addspace,"BUS_1_TR2_17KV_T1_Q",variant2)
BUS_1_TR2_17KV_T1_Q.set_writable(True)
BUS_1_TR2_17KV_T1_Q_RES = Param.add_variable(addspace,"BUS_1_TR2_17KV_T1_Q_RES",variant2)
BUS_1_TR2_17KV_T1_Q_RES.set_writable(True)
BUS_2_BUS_18KV_BUS_2_V = Param.add_variable(addspace,"BUS_2_BUS_18KV_BUS_2_V",variant2)
BUS_2_BUS_18KV_BUS_2_V.set_writable(True)
BUS_2_BUS_18KV_BUS_2_VMAX_RES = Param.add_variable(addspace,"BUS_2_BUS_18KV_BUS_2_VMAX_RES",variant2)
BUS_2_BUS_18KV_BUS_2_VMAX_RES.set_writable(True)
BUS_2_BUS_18KV_BUS_2_VMIN_RES = Param.add_variable(addspace,"BUS_2_BUS_18KV_BUS_2_VMIN_RES",variant2)
BUS_2_BUS_18KV_BUS_2_VMIN_RES.set_writable(True)
BUS_2_BUS_18KV_BUS_2_V_RES = Param.add_variable(addspace,"BUS_2_BUS_18KV_BUS_2_V_RES",variant2)
BUS_2_BUS_18KV_BUS_2_V_RES.set_writable(True)
BUS_2_CB_18KV_BREAKER2_BK = Param.add_variable(addspace,"BUS_2_CB_18KV_BREAKER2_BK",variant)
BUS_2_CB_18KV_BREAKER2_BK.set_writable(True)
BUS_2_CB_18KV_BREAKER2_BK_RES = Param.add_variable(addspace,"BUS_2_CB_18KV_BREAKER2_BK_RES",variant)
BUS_2_CB_18KV_BREAKER2_BK_RES.set_writable(True)
BUS_2_DISC_18KV_DISCONNECTOR2_BK = Param.add_variable(addspace,"BUS_2_DISC_18KV_DISCONNECTOR2_BK",variant)
BUS_2_DISC_18KV_DISCONNECTOR2_BK.set_writable(True)
BUS_2_DISC_18KV_DISCONNECTOR2_BK_RES = Param.add_variable(addspace,"BUS_2_DISC_18KV_DISCONNECTOR2_BK_RES",variant)
BUS_2_DISC_18KV_DISCONNECTOR2_BK_RES.set_writable(True)
BUS_2_GEN_18KV_G2_P_CTRL = Param.add_variable(addspace,"BUS_2_GEN_18KV_G2_P_CTRL",variant2)
BUS_2_GEN_18KV_G2_P_CTRL.set_writable(True)
BUS_2_GEN_18KV_G2_P_RES = Param.add_variable(addspace,"BUS_2_GEN_18KV_G2_P_RES",variant2)
BUS_2_GEN_18KV_G2_P_RES.set_writable(True)
BUS_2_GEN_18KV_G2_Q_RES = Param.add_variable(addspace,"BUS_2_GEN_18KV_G2_Q_RES",variant2)
BUS_2_GEN_18KV_G2_Q_RES.set_writable(True)
BUS_2_GEN_18KV_G2_V_CTRL = Param.add_variable(addspace,"BUS_2_GEN_18KV_G2_V_CTRL",variant2)
BUS_2_GEN_18KV_G2_V_CTRL.set_writable(True)
BUS_2_GEN_18KV_G2_V_RES = Param.add_variable(addspace,"BUS_2_GEN_18KV_G2_V_RES",variant2)
BUS_2_GEN_18KV_G2_V_RES.set_writable(True)
BUS_2_SWITCH_18KV_BUS_2_CUB_1_BK = Param.add_variable(addspace,"BUS_2_SWITCH_18KV_BUS_2_CUB_1_BK",variant)
BUS_2_SWITCH_18KV_BUS_2_CUB_1_BK.set_writable(True)
BUS_2_SWITCH_18KV_BUS_2_CUB_1_BK_RES = Param.add_variable(addspace,"BUS_2_SWITCH_18KV_BUS_2_CUB_1_BK_RES",variant)
BUS_2_SWITCH_18KV_BUS_2_CUB_1_BK_RES.set_writable(True)
BUS_2_TR2_18KV_T2_LD_RES = Param.add_variable(addspace,"BUS_2_TR2_18KV_T2_LD_RES",variant2)
BUS_2_TR2_18KV_T2_LD_RES.set_writable(True)
BUS_2_TR2_18KV_T2_MXL_RES = Param.add_variable(addspace,"BUS_2_TR2_18KV_T2_MXL_RES",variant2)
BUS_2_TR2_18KV_T2_MXL_RES.set_writable(True)
BUS_2_TR2_18KV_T2_P = Param.add_variable(addspace,"BUS_2_TR2_18KV_T2_P",variant2)
BUS_2_TR2_18KV_T2_P.set_writable(True)
BUS_2_TR2_18KV_T2_P_RES = Param.add_variable(addspace,"BUS_2_TR2_18KV_T2_P_RES",variant2)
BUS_2_TR2_18KV_T2_P_RES.set_writable(True)
BUS_2_TR2_18KV_T2_Q = Param.add_variable(addspace,"BUS_2_TR2_18KV_T2_Q",variant2)
BUS_2_TR2_18KV_T2_Q.set_writable(True)
BUS_2_TR2_18KV_T2_Q_RES = Param.add_variable(addspace,"BUS_2_TR2_18KV_T2_Q_RES",variant2)
BUS_2_TR2_18KV_T2_Q_RES.set_writable(True)
BUS_3_BUS_14KV_BUS_3_V = Param.add_variable(addspace,"BUS_3_BUS_14KV_BUS_3_V",variant2)
BUS_3_BUS_14KV_BUS_3_V.set_writable(True)
BUS_3_BUS_14KV_BUS_3_VMAX_RES = Param.add_variable(addspace,"BUS_3_BUS_14KV_BUS_3_VMAX_RES",variant2)
BUS_3_BUS_14KV_BUS_3_VMAX_RES.set_writable(True)
BUS_3_BUS_14KV_BUS_3_VMIN_RES = Param.add_variable(addspace,"BUS_3_BUS_14KV_BUS_3_VMIN_RES",variant2)
BUS_3_BUS_14KV_BUS_3_VMIN_RES.set_writable(True)
BUS_3_BUS_14KV_BUS_3_V_RES = Param.add_variable(addspace,"BUS_3_BUS_14KV_BUS_3_V_RES",variant2)
BUS_3_BUS_14KV_BUS_3_V_RES.set_writable(True)
BUS_3_CB_14KV_BREAKER3_BK = Param.add_variable(addspace,"BUS_3_CB_14KV_BREAKER3_BK",variant)
BUS_3_CB_14KV_BREAKER3_BK.set_writable(True)
BUS_3_CB_14KV_BREAKER3_BK_RES = Param.add_variable(addspace,"BUS_3_CB_14KV_BREAKER3_BK_RES",variant)
BUS_3_CB_14KV_BREAKER3_BK_RES.set_writable(True)
BUS_3_DISC_14KV_DISCONNECTOR3_BK = Param.add_variable(addspace,"BUS_3_DISC_14KV_DISCONNECTOR3_BK",variant)
BUS_3_DISC_14KV_DISCONNECTOR3_BK.set_writable(True)
BUS_3_DISC_14KV_DISCONNECTOR3_BK_RES = Param.add_variable(addspace,"BUS_3_DISC_14KV_DISCONNECTOR3_BK_RES",variant)
BUS_3_DISC_14KV_DISCONNECTOR3_BK_RES.set_writable(True)
BUS_3_GEN_14KV_G3_P_CTRL = Param.add_variable(addspace,"BUS_3_GEN_14KV_G3_P_CTRL",variant2)
BUS_3_GEN_14KV_G3_P_CTRL.set_writable(True)
BUS_3_GEN_14KV_G3_P_RES = Param.add_variable(addspace,"BUS_3_GEN_14KV_G3_P_RES",variant2)
BUS_3_GEN_14KV_G3_P_RES.set_writable(True)
BUS_3_GEN_14KV_G3_Q_RES = Param.add_variable(addspace,"BUS_3_GEN_14KV_G3_Q_RES",variant2)
BUS_3_GEN_14KV_G3_Q_RES.set_writable(True)
BUS_3_GEN_14KV_G3_V_CTRL = Param.add_variable(addspace,"BUS_3_GEN_14KV_G3_V_CTRL",variant2)
BUS_3_GEN_14KV_G3_V_CTRL.set_writable(True)
BUS_3_GEN_14KV_G3_V_RES = Param.add_variable(addspace,"BUS_3_GEN_14KV_G3_V_RES",variant2)
BUS_3_GEN_14KV_G3_V_RES.set_writable(True)
BUS_3_SWITCH_14KV_BUS_3_CUB_1_BK = Param.add_variable(addspace,"BUS_3_SWITCH_14KV_BUS_3_CUB_1_BK",variant)
BUS_3_SWITCH_14KV_BUS_3_CUB_1_BK.set_writable(True)
BUS_3_SWITCH_14KV_BUS_3_CUB_1_BK_RES = Param.add_variable(addspace,"BUS_3_SWITCH_14KV_BUS_3_CUB_1_BK_RES",variant)
BUS_3_SWITCH_14KV_BUS_3_CUB_1_BK_RES.set_writable(True)
BUS_3_TR2_14KV_T3_LD_RES = Param.add_variable(addspace,"BUS_3_TR2_14KV_T3_LD_RES",variant2)
BUS_3_TR2_14KV_T3_LD_RES.set_writable(True)
BUS_3_TR2_14KV_T3_MXL_RES = Param.add_variable(addspace,"BUS_3_TR2_14KV_T3_MXL_RES",variant2)
BUS_3_TR2_14KV_T3_MXL_RES.set_writable(True)
BUS_3_TR2_14KV_T3_P = Param.add_variable(addspace,"BUS_3_TR2_14KV_T3_P",variant2)
BUS_3_TR2_14KV_T3_P.set_writable(True)
BUS_3_TR2_14KV_T3_P_RES = Param.add_variable(addspace,"BUS_3_TR2_14KV_T3_P_RES",variant2)
BUS_3_TR2_14KV_T3_P_RES.set_writable(True)
BUS_3_TR2_14KV_T3_Q = Param.add_variable(addspace,"BUS_3_TR2_14KV_T3_Q",variant2)
BUS_3_TR2_14KV_T3_Q.set_writable(True)
BUS_3_TR2_14KV_T3_Q_RES = Param.add_variable(addspace,"BUS_3_TR2_14KV_T3_Q_RES",variant2)
BUS_3_TR2_14KV_T3_Q_RES.set_writable(True)
BUS_4_LNE_230KV_LINE_1_LD_RES = Param.add_variable(addspace,"BUS_4_LNE_230KV_LINE_1_LD_RES",variant2)
BUS_4_LNE_230KV_LINE_1_LD_RES.set_writable(True)
BUS_4_LNE_230KV_LINE_1_MXL_RES = Param.add_variable(addspace,"BUS_4_LNE_230KV_LINE_1_MXL_RES",variant2)
BUS_4_LNE_230KV_LINE_1_MXL_RES.set_writable(True)
BUS_4_LNE_230KV_LINE_1_P = Param.add_variable(addspace,"BUS_4_LNE_230KV_LINE_1_P",variant2)
BUS_4_LNE_230KV_LINE_1_P.set_writable(True)
BUS_4_LNE_230KV_LINE_1_P_RES = Param.add_variable(addspace,"BUS_4_LNE_230KV_LINE_1_P_RES",variant2)
BUS_4_LNE_230KV_LINE_1_P_RES.set_writable(True)
BUS_4_LNE_230KV_LINE_1_Q = Param.add_variable(addspace,"BUS_4_LNE_230KV_LINE_1_Q",variant2)
BUS_4_LNE_230KV_LINE_1_Q.set_writable(True)
BUS_4_LNE_230KV_LINE_1_Q_RES = Param.add_variable(addspace,"BUS_4_LNE_230KV_LINE_1_Q_RES",variant2)
BUS_4_LNE_230KV_LINE_1_Q_RES.set_writable(True)
BUS_4_LNE_230KV_LINE_6_LD_RES = Param.add_variable(addspace,"BUS_4_LNE_230KV_LINE_6_LD_RES",variant2)
BUS_4_LNE_230KV_LINE_6_LD_RES.set_writable(True)
BUS_4_LNE_230KV_LINE_6_MXL_RES = Param.add_variable(addspace,"BUS_4_LNE_230KV_LINE_6_MXL_RES",variant2)
BUS_4_LNE_230KV_LINE_6_MXL_RES.set_writable(True)
BUS_4_LNE_230KV_LINE_6_P = Param.add_variable(addspace,"BUS_4_LNE_230KV_LINE_6_P",variant2)
BUS_4_LNE_230KV_LINE_6_P.set_writable(True)
BUS_4_LNE_230KV_LINE_6_P_RES = Param.add_variable(addspace,"BUS_4_LNE_230KV_LINE_6_P_RES",variant2)
BUS_4_LNE_230KV_LINE_6_P_RES.set_writable(True)
BUS_4_LNE_230KV_LINE_6_Q = Param.add_variable(addspace,"BUS_4_LNE_230KV_LINE_6_Q",variant2)
BUS_4_LNE_230KV_LINE_6_Q.set_writable(True)
BUS_4_LNE_230KV_LINE_6_Q_RES = Param.add_variable(addspace,"BUS_4_LNE_230KV_LINE_6_Q_RES",variant2)
BUS_4_LNE_230KV_LINE_6_Q_RES.set_writable(True)
BUS_4_SWITCH_230KV_BUS_4_CUB_1_BK = Param.add_variable(addspace,"BUS_4_SWITCH_230KV_BUS_4_CUB_1_BK",variant)
BUS_4_SWITCH_230KV_BUS_4_CUB_1_BK.set_writable(True)
BUS_4_SWITCH_230KV_BUS_4_CUB_1_BK_RES = Param.add_variable(addspace,"BUS_4_SWITCH_230KV_BUS_4_CUB_1_BK_RES",variant)
BUS_4_SWITCH_230KV_BUS_4_CUB_1_BK_RES.set_writable(True)
BUS_4_SWITCH_230KV_BUS_4_CUB_2_BK = Param.add_variable(addspace,"BUS_4_SWITCH_230KV_BUS_4_CUB_2_BK",variant)
BUS_4_SWITCH_230KV_BUS_4_CUB_2_BK.set_writable(True)
BUS_4_SWITCH_230KV_BUS_4_CUB_2_BK_RES = Param.add_variable(addspace,"BUS_4_SWITCH_230KV_BUS_4_CUB_2_BK_RES",variant)
BUS_4_SWITCH_230KV_BUS_4_CUB_2_BK_RES.set_writable(True)
BUS_4_SWITCH_230KV_BUS_4_CUB_3_BK = Param.add_variable(addspace,"BUS_4_SWITCH_230KV_BUS_4_CUB_3_BK",variant)
BUS_4_SWITCH_230KV_BUS_4_CUB_3_BK.set_writable(True)
BUS_4_SWITCH_230KV_BUS_4_CUB_3_BK_RES = Param.add_variable(addspace,"BUS_4_SWITCH_230KV_BUS_4_CUB_3_BK_RES",variant)
BUS_4_SWITCH_230KV_BUS_4_CUB_3_BK_RES.set_writable(True)
BUS_4_TR2_230KV_T1_P = Param.add_variable(addspace,"BUS_4_TR2_230KV_T1_P",variant2)
BUS_4_TR2_230KV_T1_P.set_writable(True)
BUS_4_TR2_230KV_T1_P_RES = Param.add_variable(addspace,"BUS_4_TR2_230KV_T1_P_RES",variant2)
BUS_4_TR2_230KV_T1_P_RES.set_writable(True)
BUS_4_TR2_230KV_T1_Q = Param.add_variable(addspace,"BUS_4_TR2_230KV_T1_Q",variant2)
BUS_4_TR2_230KV_T1_Q.set_writable(True)
BUS_4_TR2_230KV_T1_Q_RES = Param.add_variable(addspace,"BUS_4_TR2_230KV_T1_Q_RES",variant2)
BUS_4_TR2_230KV_T1_Q_RES.set_writable(True)
BUS_4_TR2_T1_TAP = Param.add_variable(addspace,"BUS_4_TR2_T1_TAP",variant)
BUS_4_TR2_T1_TAP.set_writable(True)
BUS_4_TR2_T1_TAP_CTRL = Param.add_variable(addspace,"BUS_4_TR2_T1_TAP_CTRL",variant)
BUS_4_TR2_T1_TAP_CTRL.set_writable(True)
BUS_4_TR2_T1_TAP_MODE = Param.add_variable(addspace,"BUS_4_TR2_T1_TAP_MODE",variant)
BUS_4_TR2_T1_TAP_MODE.set_writable(True)
BUS_4_TR2_T1_TAP_RES = Param.add_variable(addspace,"BUS_4_TR2_T1_TAP_RES",variant)
BUS_4_TR2_T1_TAP_RES.set_writable(True)
BUS_5_LNE_230KV_LINE_1_P = Param.add_variable(addspace,"BUS_5_LNE_230KV_LINE_1_P",variant2)
BUS_5_LNE_230KV_LINE_1_P.set_writable(True)
BUS_5_LNE_230KV_LINE_1_P_RES = Param.add_variable(addspace,"BUS_5_LNE_230KV_LINE_1_P_RES",variant2)
BUS_5_LNE_230KV_LINE_1_P_RES.set_writable(True)
BUS_5_LNE_230KV_LINE_1_Q = Param.add_variable(addspace,"BUS_5_LNE_230KV_LINE_1_Q",variant2)
BUS_5_LNE_230KV_LINE_1_Q.set_writable(True)
BUS_5_LNE_230KV_LINE_1_Q_RES = Param.add_variable(addspace,"BUS_5_LNE_230KV_LINE_1_Q_RES",variant2)
BUS_5_LNE_230KV_LINE_1_Q_RES.set_writable(True)
BUS_5_LNE_230KV_LINE_2_LD_RES = Param.add_variable(addspace,"BUS_5_LNE_230KV_LINE_2_LD_RES",variant2)
BUS_5_LNE_230KV_LINE_2_LD_RES.set_writable(True)
BUS_5_LNE_230KV_LINE_2_MXL_RES = Param.add_variable(addspace,"BUS_5_LNE_230KV_LINE_2_MXL_RES",variant2)
BUS_5_LNE_230KV_LINE_2_MXL_RES.set_writable(True)
BUS_5_LNE_230KV_LINE_2_P = Param.add_variable(addspace,"BUS_5_LNE_230KV_LINE_2_P",variant2)
BUS_5_LNE_230KV_LINE_2_P.set_writable(True)
BUS_5_LNE_230KV_LINE_2_P_RES = Param.add_variable(addspace,"BUS_5_LNE_230KV_LINE_2_P_RES",variant2)
BUS_5_LNE_230KV_LINE_2_P_RES.set_writable(True)
BUS_5_LNE_230KV_LINE_2_Q = Param.add_variable(addspace,"BUS_5_LNE_230KV_LINE_2_Q",variant2)
BUS_5_LNE_230KV_LINE_2_Q.set_writable(True)
BUS_5_LNE_230KV_LINE_2_Q_RES = Param.add_variable(addspace,"BUS_5_LNE_230KV_LINE_2_Q_RES",variant2)
BUS_5_LNE_230KV_LINE_2_Q_RES.set_writable(True)
BUS_5_LOAD_230KV_LOAD_A_P_RES = Param.add_variable(addspace,"BUS_5_LOAD_230KV_LOAD_A_P_RES",variant2)
BUS_5_LOAD_230KV_LOAD_A_P_RES.set_writable(True)
BUS_5_LOAD_230KV_LOAD_A_Q_RES = Param.add_variable(addspace,"BUS_5_LOAD_230KV_LOAD_A_Q_RES",variant2)
BUS_5_LOAD_230KV_LOAD_A_Q_RES.set_writable(True)
BUS_5_LOAD_230KV_LOAD_A_V_RES = Param.add_variable(addspace,"BUS_5_LOAD_230KV_LOAD_A_V_RES",variant2)
BUS_5_LOAD_230KV_LOAD_A_V_RES.set_writable(True)
BUS_5_SWITCH_230KV_BUS_5_CUB_1_BK = Param.add_variable(addspace,"BUS_5_SWITCH_230KV_BUS_5_CUB_1_BK",variant)
BUS_5_SWITCH_230KV_BUS_5_CUB_1_BK.set_writable(True)
BUS_5_SWITCH_230KV_BUS_5_CUB_1_BK_RES = Param.add_variable(addspace,"BUS_5_SWITCH_230KV_BUS_5_CUB_1_BK_RES",variant)
BUS_5_SWITCH_230KV_BUS_5_CUB_1_BK_RES.set_writable(True)
BUS_5_SWITCH_230KV_BUS_5_CUB_2_BK = Param.add_variable(addspace,"BUS_5_SWITCH_230KV_BUS_5_CUB_2_BK",variant)
BUS_5_SWITCH_230KV_BUS_5_CUB_2_BK.set_writable(True)
BUS_5_SWITCH_230KV_BUS_5_CUB_2_BK_RES = Param.add_variable(addspace,"BUS_5_SWITCH_230KV_BUS_5_CUB_2_BK_RES",variant)
BUS_5_SWITCH_230KV_BUS_5_CUB_2_BK_RES.set_writable(True)
BUS_5_SWITCH_230KV_BUS_5_CUB_3_BK = Param.add_variable(addspace,"BUS_5_SWITCH_230KV_BUS_5_CUB_3_BK",variant)
BUS_5_SWITCH_230KV_BUS_5_CUB_3_BK.set_writable(True)
BUS_5_SWITCH_230KV_BUS_5_CUB_3_BK_RES = Param.add_variable(addspace,"BUS_5_SWITCH_230KV_BUS_5_CUB_3_BK_RES",variant)
BUS_5_SWITCH_230KV_BUS_5_CUB_3_BK_RES.set_writable(True)
BUS_6_LNE_230KV_LINE_5_LD_RES = Param.add_variable(addspace,"BUS_6_LNE_230KV_LINE_5_LD_RES",variant2)
BUS_6_LNE_230KV_LINE_5_LD_RES.set_writable(True)
BUS_6_LNE_230KV_LINE_5_MXL_RES = Param.add_variable(addspace,"BUS_6_LNE_230KV_LINE_5_MXL_RES",variant2)
BUS_6_LNE_230KV_LINE_5_MXL_RES.set_writable(True)
BUS_6_LNE_230KV_LINE_5_P = Param.add_variable(addspace,"BUS_6_LNE_230KV_LINE_5_P",variant2)
BUS_6_LNE_230KV_LINE_5_P.set_writable(True)
BUS_6_LNE_230KV_LINE_5_P_RES = Param.add_variable(addspace,"BUS_6_LNE_230KV_LINE_5_P_RES",variant2)
BUS_6_LNE_230KV_LINE_5_P_RES.set_writable(True)
BUS_6_LNE_230KV_LINE_5_Q = Param.add_variable(addspace,"BUS_6_LNE_230KV_LINE_5_Q",variant2)
BUS_6_LNE_230KV_LINE_5_Q.set_writable(True)
BUS_6_LNE_230KV_LINE_5_Q_RES = Param.add_variable(addspace,"BUS_6_LNE_230KV_LINE_5_Q_RES",variant2)
BUS_6_LNE_230KV_LINE_5_Q_RES.set_writable(True)
BUS_6_LNE_230KV_LINE_6_P = Param.add_variable(addspace,"BUS_6_LNE_230KV_LINE_6_P",variant2)
BUS_6_LNE_230KV_LINE_6_P.set_writable(True)
BUS_6_LNE_230KV_LINE_6_P_RES = Param.add_variable(addspace,"BUS_6_LNE_230KV_LINE_6_P_RES",variant2)
BUS_6_LNE_230KV_LINE_6_P_RES.set_writable(True)
BUS_6_LNE_230KV_LINE_6_Q = Param.add_variable(addspace,"BUS_6_LNE_230KV_LINE_6_Q",variant2)
BUS_6_LNE_230KV_LINE_6_Q.set_writable(True)
BUS_6_LNE_230KV_LINE_6_Q_RES = Param.add_variable(addspace,"BUS_6_LNE_230KV_LINE_6_Q_RES",variant2)
BUS_6_LNE_230KV_LINE_6_Q_RES.set_writable(True)
BUS_6_LOAD_230KV_LOAD_B_P_RES = Param.add_variable(addspace,"BUS_6_LOAD_230KV_LOAD_B_P_RES",variant2)
BUS_6_LOAD_230KV_LOAD_B_P_RES.set_writable(True)
BUS_6_LOAD_230KV_LOAD_B_Q_RES = Param.add_variable(addspace,"BUS_6_LOAD_230KV_LOAD_B_Q_RES",variant2)
BUS_6_LOAD_230KV_LOAD_B_Q_RES.set_writable(True)
BUS_6_LOAD_230KV_LOAD_B_V_RES = Param.add_variable(addspace,"BUS_6_LOAD_230KV_LOAD_B_V_RES",variant2)
BUS_6_LOAD_230KV_LOAD_B_V_RES.set_writable(True)
BUS_6_SWITCH_230KV_BUS_6_CUB_1_BK = Param.add_variable(addspace,"BUS_6_SWITCH_230KV_BUS_6_CUB_1_BK",variant)
BUS_6_SWITCH_230KV_BUS_6_CUB_1_BK.set_writable(True)
BUS_6_SWITCH_230KV_BUS_6_CUB_1_BK_RES = Param.add_variable(addspace,"BUS_6_SWITCH_230KV_BUS_6_CUB_1_BK_RES",variant)
BUS_6_SWITCH_230KV_BUS_6_CUB_1_BK_RES.set_writable(True)
BUS_6_SWITCH_230KV_BUS_6_CUB_2_BK = Param.add_variable(addspace,"BUS_6_SWITCH_230KV_BUS_6_CUB_2_BK",variant)
BUS_6_SWITCH_230KV_BUS_6_CUB_2_BK.set_writable(True)
BUS_6_SWITCH_230KV_BUS_6_CUB_2_BK_RES = Param.add_variable(addspace,"BUS_6_SWITCH_230KV_BUS_6_CUB_2_BK_RES",variant)
BUS_6_SWITCH_230KV_BUS_6_CUB_2_BK_RES.set_writable(True)
BUS_6_SWITCH_230KV_BUS_6_CUB_3_BK = Param.add_variable(addspace,"BUS_6_SWITCH_230KV_BUS_6_CUB_3_BK",variant)
BUS_6_SWITCH_230KV_BUS_6_CUB_3_BK.set_writable(True)
BUS_6_SWITCH_230KV_BUS_6_CUB_3_BK_RES = Param.add_variable(addspace,"BUS_6_SWITCH_230KV_BUS_6_CUB_3_BK_RES",variant)
BUS_6_SWITCH_230KV_BUS_6_CUB_3_BK_RES.set_writable(True)
BUS_7_LNE_230KV_LINE_2_P = Param.add_variable(addspace,"BUS_7_LNE_230KV_LINE_2_P",variant2)
BUS_7_LNE_230KV_LINE_2_P.set_writable(True)
BUS_7_LNE_230KV_LINE_2_P_RES = Param.add_variable(addspace,"BUS_7_LNE_230KV_LINE_2_P_RES",variant2)
BUS_7_LNE_230KV_LINE_2_P_RES.set_writable(True)
BUS_7_LNE_230KV_LINE_2_Q = Param.add_variable(addspace,"BUS_7_LNE_230KV_LINE_2_Q",variant2)
BUS_7_LNE_230KV_LINE_2_Q.set_writable(True)
BUS_7_LNE_230KV_LINE_2_Q_RES = Param.add_variable(addspace,"BUS_7_LNE_230KV_LINE_2_Q_RES",variant2)
BUS_7_LNE_230KV_LINE_2_Q_RES.set_writable(True)
BUS_7_LNE_230KV_LINE_3_P = Param.add_variable(addspace,"BUS_7_LNE_230KV_LINE_3_P",variant2)
BUS_7_LNE_230KV_LINE_3_P.set_writable(True)
BUS_7_LNE_230KV_LINE_3_P_RES = Param.add_variable(addspace,"BUS_7_LNE_230KV_LINE_3_P_RES",variant2)
BUS_7_LNE_230KV_LINE_3_P_RES.set_writable(True)
BUS_7_LNE_230KV_LINE_3_Q = Param.add_variable(addspace,"BUS_7_LNE_230KV_LINE_3_Q",variant2)
BUS_7_LNE_230KV_LINE_3_Q.set_writable(True)
BUS_7_LNE_230KV_LINE_3_Q_RES = Param.add_variable(addspace,"BUS_7_LNE_230KV_LINE_3_Q_RES",variant2)
BUS_7_LNE_230KV_LINE_3_Q_RES.set_writable(True)
BUS_7_SWITCH_230KV_BUS_7_CUB_1_BK = Param.add_variable(addspace,"BUS_7_SWITCH_230KV_BUS_7_CUB_1_BK",variant)
BUS_7_SWITCH_230KV_BUS_7_CUB_1_BK.set_writable(True)
BUS_7_SWITCH_230KV_BUS_7_CUB_1_BK_RES = Param.add_variable(addspace,"BUS_7_SWITCH_230KV_BUS_7_CUB_1_BK_RES",variant)
BUS_7_SWITCH_230KV_BUS_7_CUB_1_BK_RES.set_writable(True)
BUS_7_SWITCH_230KV_BUS_7_CUB_2_BK = Param.add_variable(addspace,"BUS_7_SWITCH_230KV_BUS_7_CUB_2_BK",variant)
BUS_7_SWITCH_230KV_BUS_7_CUB_2_BK.set_writable(True)
BUS_7_SWITCH_230KV_BUS_7_CUB_2_BK_RES = Param.add_variable(addspace,"BUS_7_SWITCH_230KV_BUS_7_CUB_2_BK_RES",variant)
BUS_7_SWITCH_230KV_BUS_7_CUB_2_BK_RES.set_writable(True)
BUS_7_SWITCH_230KV_BUS_7_CUB_3_BK = Param.add_variable(addspace,"BUS_7_SWITCH_230KV_BUS_7_CUB_3_BK",variant)
BUS_7_SWITCH_230KV_BUS_7_CUB_3_BK.set_writable(True)
BUS_7_SWITCH_230KV_BUS_7_CUB_3_BK_RES = Param.add_variable(addspace,"BUS_7_SWITCH_230KV_BUS_7_CUB_3_BK_RES",variant)
BUS_7_SWITCH_230KV_BUS_7_CUB_3_BK_RES.set_writable(True)
BUS_7_TR2_230KV_T2_P = Param.add_variable(addspace,"BUS_7_TR2_230KV_T2_P",variant2)
BUS_7_TR2_230KV_T2_P.set_writable(True)
BUS_7_TR2_230KV_T2_P_RES = Param.add_variable(addspace,"BUS_7_TR2_230KV_T2_P_RES",variant2)
BUS_7_TR2_230KV_T2_P_RES.set_writable(True)
BUS_7_TR2_230KV_T2_Q = Param.add_variable(addspace,"BUS_7_TR2_230KV_T2_Q",variant2)
BUS_7_TR2_230KV_T2_Q.set_writable(True)
BUS_7_TR2_230KV_T2_Q_RES = Param.add_variable(addspace,"BUS_7_TR2_230KV_T2_Q_RES",variant2)
BUS_7_TR2_230KV_T2_Q_RES.set_writable(True)
BUS_7_TR2_T2_TAP = Param.add_variable(addspace,"BUS_7_TR2_T2_TAP",variant)
BUS_7_TR2_T2_TAP.set_writable(True)
BUS_7_TR2_T2_TAP_CTRL = Param.add_variable(addspace,"BUS_7_TR2_T2_TAP_CTRL",variant)
BUS_7_TR2_T2_TAP_CTRL.set_writable(True)
BUS_7_TR2_T2_TAP_MODE = Param.add_variable(addspace,"BUS_7_TR2_T2_TAP_MODE",variant)
BUS_7_TR2_T2_TAP_MODE.set_writable(True)
BUS_7_TR2_T2_TAP_RES = Param.add_variable(addspace,"BUS_7_TR2_T2_TAP_RES",variant)
BUS_7_TR2_T2_TAP_RES.set_writable(True)
BUS_8_LNE_230KV_LINE_3_LD_RES = Param.add_variable(addspace,"BUS_8_LNE_230KV_LINE_3_LD_RES",variant2)
BUS_8_LNE_230KV_LINE_3_LD_RES.set_writable(True)
BUS_8_LNE_230KV_LINE_3_MXL_RES = Param.add_variable(addspace,"BUS_8_LNE_230KV_LINE_3_MXL_RES",variant2)
BUS_8_LNE_230KV_LINE_3_MXL_RES.set_writable(True)
BUS_8_LNE_230KV_LINE_3_P = Param.add_variable(addspace,"BUS_8_LNE_230KV_LINE_3_P",variant2)
BUS_8_LNE_230KV_LINE_3_P.set_writable(True)
BUS_8_LNE_230KV_LINE_3_P_RES = Param.add_variable(addspace,"BUS_8_LNE_230KV_LINE_3_P_RES",variant2)
BUS_8_LNE_230KV_LINE_3_P_RES.set_writable(True)
BUS_8_LNE_230KV_LINE_3_Q = Param.add_variable(addspace,"BUS_8_LNE_230KV_LINE_3_Q",variant2)
BUS_8_LNE_230KV_LINE_3_Q.set_writable(True)
BUS_8_LNE_230KV_LINE_3_Q_RES = Param.add_variable(addspace,"BUS_8_LNE_230KV_LINE_3_Q_RES",variant2)
BUS_8_LNE_230KV_LINE_3_Q_RES.set_writable(True)
BUS_8_LNE_230KV_LINE_4_P = Param.add_variable(addspace,"BUS_8_LNE_230KV_LINE_4_P",variant2)
BUS_8_LNE_230KV_LINE_4_P.set_writable(True)
BUS_8_LNE_230KV_LINE_4_P_RES = Param.add_variable(addspace,"BUS_8_LNE_230KV_LINE_4_P_RES",variant2)
BUS_8_LNE_230KV_LINE_4_P_RES.set_writable(True)
BUS_8_LNE_230KV_LINE_4_Q = Param.add_variable(addspace,"BUS_8_LNE_230KV_LINE_4_Q",variant2)
BUS_8_LNE_230KV_LINE_4_Q.set_writable(True)
BUS_8_LNE_230KV_LINE_4_Q_RES = Param.add_variable(addspace,"BUS_8_LNE_230KV_LINE_4_Q_RES",variant2)
BUS_8_LNE_230KV_LINE_4_Q_RES.set_writable(True)
BUS_8_LOAD_230KV_LOAD_C_P_RES = Param.add_variable(addspace,"BUS_8_LOAD_230KV_LOAD_C_P_RES",variant2)
BUS_8_LOAD_230KV_LOAD_C_P_RES.set_writable(True)
BUS_8_LOAD_230KV_LOAD_C_Q_RES = Param.add_variable(addspace,"BUS_8_LOAD_230KV_LOAD_C_Q_RES",variant2)
BUS_8_LOAD_230KV_LOAD_C_Q_RES.set_writable(True)
BUS_8_LOAD_230KV_LOAD_C_V_RES = Param.add_variable(addspace,"BUS_8_LOAD_230KV_LOAD_C_V_RES",variant2)
BUS_8_LOAD_230KV_LOAD_C_V_RES.set_writable(True)
BUS_8_SWITCH_230KV_BUS_8_CUB_1_BK = Param.add_variable(addspace,"BUS_8_SWITCH_230KV_BUS_8_CUB_1_BK",variant)
BUS_8_SWITCH_230KV_BUS_8_CUB_1_BK.set_writable(True)
BUS_8_SWITCH_230KV_BUS_8_CUB_1_BK_RES = Param.add_variable(addspace,"BUS_8_SWITCH_230KV_BUS_8_CUB_1_BK_RES",variant)
BUS_8_SWITCH_230KV_BUS_8_CUB_1_BK_RES.set_writable(True)
BUS_8_SWITCH_230KV_BUS_8_CUB_2_BK = Param.add_variable(addspace,"BUS_8_SWITCH_230KV_BUS_8_CUB_2_BK",variant)
BUS_8_SWITCH_230KV_BUS_8_CUB_2_BK.set_writable(True)
BUS_8_SWITCH_230KV_BUS_8_CUB_2_BK_RES = Param.add_variable(addspace,"BUS_8_SWITCH_230KV_BUS_8_CUB_2_BK_RES",variant)
BUS_8_SWITCH_230KV_BUS_8_CUB_2_BK_RES.set_writable(True)
BUS_8_SWITCH_230KV_BUS_8_CUB_3_BK = Param.add_variable(addspace,"BUS_8_SWITCH_230KV_BUS_8_CUB_3_BK",variant)
BUS_8_SWITCH_230KV_BUS_8_CUB_3_BK.set_writable(True)
BUS_8_SWITCH_230KV_BUS_8_CUB_3_BK_RES = Param.add_variable(addspace,"BUS_8_SWITCH_230KV_BUS_8_CUB_3_BK_RES",variant)
BUS_8_SWITCH_230KV_BUS_8_CUB_3_BK_RES.set_writable(True)
BUS_9_LNE_230KV_LINE_4_LD_RES = Param.add_variable(addspace,"BUS_9_LNE_230KV_LINE_4_LD_RES",variant2)
BUS_9_LNE_230KV_LINE_4_LD_RES.set_writable(True)
BUS_9_LNE_230KV_LINE_4_MXL_RES = Param.add_variable(addspace,"BUS_9_LNE_230KV_LINE_4_MXL_RES",variant2)
BUS_9_LNE_230KV_LINE_4_MXL_RES.set_writable(True)
BUS_9_LNE_230KV_LINE_4_P = Param.add_variable(addspace,"BUS_9_LNE_230KV_LINE_4_P",variant2)
BUS_9_LNE_230KV_LINE_4_P.set_writable(True)
BUS_9_LNE_230KV_LINE_4_P_RES = Param.add_variable(addspace,"BUS_9_LNE_230KV_LINE_4_P_RES",variant2)
BUS_9_LNE_230KV_LINE_4_P_RES.set_writable(True)
BUS_9_LNE_230KV_LINE_4_Q = Param.add_variable(addspace,"BUS_9_LNE_230KV_LINE_4_Q",variant2)
BUS_9_LNE_230KV_LINE_4_Q.set_writable(True)
BUS_9_LNE_230KV_LINE_4_Q_RES = Param.add_variable(addspace,"BUS_9_LNE_230KV_LINE_4_Q_RES",variant2)
BUS_9_LNE_230KV_LINE_4_Q_RES.set_writable(True)
BUS_9_LNE_230KV_LINE_5_P = Param.add_variable(addspace,"BUS_9_LNE_230KV_LINE_5_P",variant2)
BUS_9_LNE_230KV_LINE_5_P.set_writable(True)
BUS_9_LNE_230KV_LINE_5_P_RES = Param.add_variable(addspace,"BUS_9_LNE_230KV_LINE_5_P_RES",variant2)
BUS_9_LNE_230KV_LINE_5_P_RES.set_writable(True)
BUS_9_LNE_230KV_LINE_5_Q = Param.add_variable(addspace,"BUS_9_LNE_230KV_LINE_5_Q",variant2)
BUS_9_LNE_230KV_LINE_5_Q.set_writable(True)
BUS_9_LNE_230KV_LINE_5_Q_RES = Param.add_variable(addspace,"BUS_9_LNE_230KV_LINE_5_Q_RES",variant2)
BUS_9_LNE_230KV_LINE_5_Q_RES.set_writable(True)
BUS_9_SWITCH_230KV_BUS_9_CUB_1_BK = Param.add_variable(addspace,"BUS_9_SWITCH_230KV_BUS_9_CUB_1_BK",variant)
BUS_9_SWITCH_230KV_BUS_9_CUB_1_BK.set_writable(True)
BUS_9_SWITCH_230KV_BUS_9_CUB_1_BK_RES = Param.add_variable(addspace,"BUS_9_SWITCH_230KV_BUS_9_CUB_1_BK_RES",variant)
BUS_9_SWITCH_230KV_BUS_9_CUB_1_BK_RES.set_writable(True)
BUS_9_SWITCH_230KV_BUS_9_CUB_2_BK = Param.add_variable(addspace,"BUS_9_SWITCH_230KV_BUS_9_CUB_2_BK",variant)
BUS_9_SWITCH_230KV_BUS_9_CUB_2_BK.set_writable(True)
BUS_9_SWITCH_230KV_BUS_9_CUB_2_BK_RES = Param.add_variable(addspace,"BUS_9_SWITCH_230KV_BUS_9_CUB_2_BK_RES",variant)
BUS_9_SWITCH_230KV_BUS_9_CUB_2_BK_RES.set_writable(True)
BUS_9_SWITCH_230KV_BUS_9_CUB_3_BK = Param.add_variable(addspace,"BUS_9_SWITCH_230KV_BUS_9_CUB_3_BK",variant)
BUS_9_SWITCH_230KV_BUS_9_CUB_3_BK.set_writable(True)
BUS_9_SWITCH_230KV_BUS_9_CUB_3_BK_RES = Param.add_variable(addspace,"BUS_9_SWITCH_230KV_BUS_9_CUB_3_BK_RES",variant)
BUS_9_SWITCH_230KV_BUS_9_CUB_3_BK_RES.set_writable(True)
BUS_9_TR2_230KV_T3_P = Param.add_variable(addspace,"BUS_9_TR2_230KV_T3_P",variant2)
BUS_9_TR2_230KV_T3_P.set_writable(True)
BUS_9_TR2_230KV_T3_P_RES = Param.add_variable(addspace,"BUS_9_TR2_230KV_T3_P_RES",variant2)
BUS_9_TR2_230KV_T3_P_RES.set_writable(True)
BUS_9_TR2_230KV_T3_Q = Param.add_variable(addspace,"BUS_9_TR2_230KV_T3_Q",variant2)
BUS_9_TR2_230KV_T3_Q.set_writable(True)
BUS_9_TR2_230KV_T3_Q_RES = Param.add_variable(addspace,"BUS_9_TR2_230KV_T3_Q_RES",variant2)
BUS_9_TR2_230KV_T3_Q_RES.set_writable(True)
BUS_9_TR2_T3_TAP = Param.add_variable(addspace,"BUS_9_TR2_T3_TAP",variant)
BUS_9_TR2_T3_TAP.set_writable(True)
BUS_9_TR2_T3_TAP_CTRL = Param.add_variable(addspace,"BUS_9_TR2_T3_TAP_CTRL",variant)
BUS_9_TR2_T3_TAP_CTRL.set_writable(True)
BUS_9_TR2_T3_TAP_MODE = Param.add_variable(addspace,"BUS_9_TR2_T3_TAP_MODE",variant)
BUS_9_TR2_T3_TAP_MODE.set_writable(True)
BUS_9_TR2_T3_TAP_RES = Param.add_variable(addspace,"BUS_9_TR2_T3_TAP_RES",variant)
BUS_9_TR2_T3_TAP_RES.set_writable(True)
GEN_PSUM_RES = Param.add_variable(addspace,"GEN_PSUM_RES",variant2)
GEN_PSUM_RES.set_writable(True)
MODE = Param.add_variable(addspace,"MODE",variant)
MODE.set_writable(True)
READY = Param.add_variable(addspace,"READY",variant)
READY.set_writable(True)



server.start()

print("Server start at {}".format(url))

"""
try:
    while True:
        i = 1
        while i < 5:
            time.sleep(0.001)

finally:
    #close connection, remove subcsriptions, etc
    server.stop()

"""


"""
i = 1
while i < 5:

    time.sleep(0.001)

 

server.stop()
"""


"""
idx = server.register_namespace(uri)
server.start()
objects = server.get_objects_node()
self.pfGroup = objects.add_object(idx, "PF")
pfVar = self.pfGroup.add_variable(idx, var.aliasName, variant)

"""

